language: node_js
node_js:
  - '8'

install:
  - npm install -g coveralls
  - npm install
  - npm install react-molecule mobx mobx-react

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
# sudo: false
